FROM debian:latest
MAINTAINER Ryan Kurte <ryankurte@gmail.com>
LABEL Description="Docker image for building latex projects"

RUN apt-get update -y && \
    apt-get upgrade -y && \
    apt-get install -y make latexmk pandoc texlive-full



