name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        image:
          - arm-embedded
          - aws-cli
          - esp32
          - ghdl
          - gitbook
          - latex
          - mdbook
          - native-dev
          - rust-embedded
          - rust-i386
          - vim
          - zip

    steps:
    - uses: actions/checkout@v2
    - name: Login to Docker Hub (to avoid rate-limiting)
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Build ${{ matrix.image }} docker image
      run: docker build --tag ${{ matrix.image }}:$(date +%s) ${{ matrix.image }}
    - name: Publish ${{ matrix.image }} to ghcr.io/ryankurte/${{ matrix.image }}:$(date +%s)
      run: |
        docker tag ${{ matrix.image }}:$(date +%s) ghcr.io/ryankurte/${{ matrix.image }}:$(date +%s)
        docker push ghcr.io/ryankurte/${{ matrix.image }}:$(date +%s)
  
