name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        image:
          - arm-embedded
          - aws-cli
          - esp32
          - ghdl
          - gitbook
          - latex
          - mdbook
          - native-dev
          - rust-embedded
          - rust-i386
          - vim
          - zip

    steps:
    - uses: actions/checkout@v2
    
    - name: Check for dockerfile changes
      uses: marceloprado/has-changed-path@v1
      id: changes
      with:
        paths: ${{ matrix.image }}
    
    - name: Login to Docker Hub (to avoid rate-limiting)
      uses: docker/login-action@v1
      #if: steps.changes.outputs.changed == 'true'
      with:
        username: ryankurte
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        
    - name: Login to GHCR (for publishing)
      uses: docker/login-action@v1
      #if: steps.changes.outputs.changed == 'true'
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
          
    - name: Build ${{ matrix.image }} image
      #if: steps.changes.outputs.changed == 'true'
      run: docker build --tag ${{ matrix.image }}:${GITHUB_SHA::8} ${{ matrix.image }}
      
    - name: Publish ${{ matrix.image }} to ghcr
      #if: steps.changes.outputs.changed == 'true'
      run: |
        docker tag ${{ matrix.image }}:${GITHUB_SHA::8} ghcr.io/ryankurte/${{ matrix.image }}:${GITHUB_SHA::8}
        docker push ghcr.io/ryankurte/${{ matrix.image }}:${GITHUB_SHA::8}
        
    - name: Publish ${{ matrix.image }} to dockerhub
      #if: steps.changes.outputs.changed == 'true'
      run: |
        docker tag ${{ matrix.image }}:${GITHUB_SHA::8} docker.io/ryankurte/${{ matrix.image }}:${GITHUB_SHA::8}
        docker push docker.io/ryankurte/${{ matrix.image }}:${GITHUB_SHA::8}
        
